version:  "3"
services:
  blog-db:
    image: postgres:14.5
    container_name: blog-db
    restart: always
    ports:
    - "127.0.0.1:5432:5432"
    expose:
    - "5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: blog
      POSTGRES_USER: postgres

  blog-migrations:
    image: amacneil/dbmate
    container_name: blog-migrations
    env_file:
    - .env
    volumes:
    - ./db:/db
    depends_on: [blog-db]
    command: [up]
    network_mode: host

volumes:
  db:
